export const environment = {
  production: true,
  apiUrl: "https://senta.cjvt.si/senta",
  simplifyEndpoint: "/simplify",
  longWordsEndpoint: "/long-words",
  refreshStatsEndpoint: "/refresh-stats",
  reactionsEndpoint: "/likes",
  longWordsDefaultLength: 7,
  exampleText: "Ognjenik (tudi vulkan) je geološka površinska oblika, ki se največkrat pojavlja kot gora ali hrib. Nastane zaradi akumulacije magmatskega materiala, izbruhanega iz notranjosti Zemlje zaradi tamkajšnjih pritiskov. Ognjenik ima lahko poleg najbolj znane stožčaste oblike tudi zelo položna pobočja, ki tvorijo vzpetino v obliki ščita, ali pa je celo popolnoma raven. Velika večina ognjenikov se nahaja pod morsko gladino. V preteklih 10.000 letih je bilo na Zemlji dejavnih 1511 ognjenikov, od katerih jih je v času dokumentirane zgodovine bruhalo 539. Vsako leto pa je ognjeniško aktivnost moč opaziti pri približno 50 do 60 vulkanih. Ognjeniški izbruhi predstavljajo veliko naravno nevarnost za okoliško prebivalstvo, in sicer zaradi tokov lave ali padajočega pepela, pa tudi strupenih plinov. Vsi ognjeniki nastajajo z akumulacijo (usedanjem) magme, ki izbruhne iz odprtin v površini Zemlje, ognjeniških dimnikov. Ti lahko tvorijo tudi celotno ognjeniško verigo. Material, ki kasneje izbruhne, je ustvarjen globoko pod površino v zgornjem delu plašča, včasih pa tudi v bazi Zemljine skorje, navadno pri globinah med 80 in 100 kilometri pod površjem. Ko se delci magme oblikujejo na takšnih globinah, se prično dvigovati. Ta proces v celoti še ni poznan, vsekakor pa temelji na razliki gostot med tekočo magmo in okoliškimi trdnimi kamninami. Prva se pri dvigovanju združuje v večje delce, ki potujejo do površine. Slednje ne prehajajo postopoma in zmerno, pač pa se poprej zbirajo v zbiralniku, imenovanem magmatsko ognjišče, tudi ognjeniški kotel; ko je ta napolnjen in se v njem ustvari dovolj velik pritisk, se material z izbruhom prebije na površje. Izbruhane snovi se v veliki meri odložijo v okolici odprtine (dimnika), kar je osnova za vzpetino.",
};
